Repository UK-Export-Finance/tfs-api, pull requests merged in 2023-07, with the labels that each got.

#331 revert: reverted "temporary fix - set static value as todays date"
  package-lock.json
  package.json
  src/modules/date/current-date.provider.ts
  src/modules/date/date-string.transformations.test.ts
  src/modules/deal-guarantee/deal-guarantee.service.create-guarantee.test.ts
  src/modules/deal-investor/deal-investor.service.create-investor.test.ts
  src/modules/deal/deal.service.create-deal.test.ts
  src/modules/deal/deal.service.ts
  src/modules/facility-guarantee/facility-guarantee.service.create-guarantee.test.ts
  src/modules/facility-loan/accrual-schedule.builder.test.ts
  src/modules/facility-loan/facility-loan.service.create-loan.test.ts
  src/modules/facility/facility.service.create-facility.test-parts/create-facility-effective-date-tests.ts
  src/modules/facility/facility.service.ts
  test/deal-guarantee/post-deal-guarantee.api-test.ts
  test/deal-investor/post-deal-investors.api-test.ts
  test/deal/post-deal.api-test.ts
  test/facility-guarantee/post-facility-guarantee.api-test.ts
  test/support/generator/create-deal-generator.ts
  test/support/generator/create-facility-generator.ts
  test/support/generator/update-facility-generator.ts
Labels: Type: Fix

#334 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: Type: chore

#338 fix(iac): ACR
  .github/workflows/deploy.sh
  Dockerfile
  package-lock.json
Labels: Infrastrucre

#341 fix(iac): IaC
  .github/dependabot.yml
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  .gitignore
  package-lock.json
Labels: Infrastrucre

#344 chore(deps): dependencies update
  package-lock.json
  package.json
Labels: Type: chore

#343 feat(APIM-468): Allow numeric environment variables to be set to 0
  src/config/acbs-authentication.config.ts
  src/config/acbs.config.test.ts
  src/config/acbs.config.ts
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/config/mdm.config.ts
  src/helpers/get-int-config.helper.test.ts
  src/helpers/get-int-config.ts
  test/common-tests/environment-variable-parsing-unit-tests.ts
Labels: Type: Feature

#351 feat(env): environment variables
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
Labels: Infrastrucre
