Repository UK-Export-Finance/tfs-api, pull requests merged in 2023-03, with the labels that each got.

#12 chore(npm-update): dependencies update
  package-lock.json
Labels: Type: Chore

#11 feat(APIM-76): add endpoint to get external ratings for parties
  .cspell.json
  .env.sample
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/config/acbs.config.ts
  src/config/app.config.ts
  src/config/doc.config.ts
  src/config/load-dotenv.ts
  src/helpers/date-string.type.ts
  src/main.ts
  src/modules/acbs-adapter/acbs-adapter.module.ts
  src/modules/acbs-adapter/acbs-exception-transform.interceptor.test.ts
  src/modules/acbs-adapter/acbs-exception-transform.interceptor.ts
  src/modules/acbs/acbs-authentication.service.test.ts
  src/modules/acbs/acbs-authentication.service.ts
  src/modules/acbs/acbs.module.ts
  src/modules/acbs/acbs.service.test.ts
  src/modules/acbs/acbs.service.ts
  src/modules/acbs/dto/acbs-party-external-ratings-response.dto.ts
  src/modules/acbs/exception/acbs-authentication-failed.exception.test.ts
  src/modules/acbs/exception/acbs-authentication-failed.exception.ts
  src/modules/acbs/exception/acbs-resource-not-found.exception.test.ts
  src/modules/acbs/exception/acbs-resource-not-found.exception.ts
  src/modules/acbs/exception/acbs.exception.test.ts
  src/modules/acbs/exception/acbs.exception.ts
  src/modules/party-external-rating/dto/get-party-external-ratings-response.dto.ts
  src/modules/party-external-rating/party-external-rating.controller.test.ts
  src/modules/party-external-rating/party-external-rating.controller.ts
  src/modules/party-external-rating/party-external-rating.interface.ts
  src/modules/party-external-rating/party-external-rating.module.ts
  src/modules/party-external-rating/party-external-rating.service.test.ts
  src/modules/party-external-rating/party-external-rating.service.ts
  src/modules/tfs.module.ts
  src/swagger.ts
  test/app.api-test.ts
  test/party-external-rating/get-party-external-ratings.api-test.ts
  test/setup/override-environment-variables.ts
  test/support/api.ts
  test/support/app.ts
  test/support/environment-variables.ts
  test/support/generator/party-external-rating-generator.ts
  test/support/generator/random-value-generator.ts
  test/support/random-value-generator.ts
Labels: Type: Feature

#16 fix(fossa-gha): reverted back to public runner
  .cspell.json
  .github/workflows/sca.yml
  .github/workflows/test.yml
Labels: Type: Fix

#20 chore(deps): update all NPM packages
  commitlint.config.js
  package-lock.json
  package.json
  src/main.module.ts
  src/swagger.ts
Labels: Type: Chore

#22 chore(npm-update): dependency update
  package-lock.json
Labels: Type: Chore

#21 feat: added authentication using API Key
  .env.sample
  .eslintrc.json
  README.md
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/config/app.config.ts
  src/constants/acbs.constant.ts
  src/constants/application.constant.ts
  src/constants/auth.constant.ts
  src/constants/index.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.test.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guard/api-key.guard.ts
  src/modules/auth/strategy/api-key.strategy.test.ts
  src/modules/auth/strategy/api-key.strategy.ts
  src/modules/party/party.module.ts
  src/modules/tfs.module.ts
  test/common-tests/client-authentication-api-tests.ts
  test/docs/get-docs-yaml.api-test.ts
  test/party-external-rating/get-party-external-ratings.api-test.ts
  test/party/get-parties-by-search-text.api-test.ts
  test/party/get-party-by-party-identifier.api-test.ts
  test/support/api.ts
  test/support/environment-variables.ts
  tsconfig.json
Labels: Type: Feature, Type: Security

#28 feat(APIM-81): Add get deal investor endpoint
  src/constants/enum.constant.ts
  src/constants/enums/lender-type-code.ts
  src/constants/enums/portfolio.ts
  src/constants/examples.constant.ts
  src/constants/index.ts
  src/constants/ukef-id.constant.ts
  src/helpers/index.ts
  src/helpers/ukef-id.type.ts
  src/modules/acbs/acbs-deal-party.service.test.ts
  src/modules/acbs/acbs-deal-party.service.ts
  src/modules/acbs/acbs.module.ts
  src/modules/acbs/dto/acbs-get-deal-party-response.dto.ts
  src/modules/deal-investor/deal-investor.controller.test.ts
  src/modules/deal-investor/deal-investor.controller.ts
  src/modules/deal-investor/deal-investor.interface.ts
  src/modules/deal-investor/deal-investor.module.ts
  src/modules/deal-investor/deal-investor.service.get-investors.test.ts
  src/modules/deal-investor/deal-investor.service.ts
  src/modules/deal-investor/dto/deal-investor-response.dto.ts
  src/modules/deal-investor/dto/get-deals-investors-params.dto.ts
  src/modules/tfs.module.ts
  test/deal-investor/get-deal-investors-by-deal-identifier.api-test.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/support/generator/deal-investor-generator.ts
  test/support/generator/random-value-generator.ts
Labels: Type: Feature

#32 chore(npm-update): added --save flag
  package-lock.json
  package.json
Labels: Type: Chore

#35 feat(dependabot): added dependabot.yml GHA
  .github/workflows/dependabot.yml
Labels: Type: Feature, Type: Security, dependencies

#37 fix(dependabot): correct location
  .github/dependabot.yml
Labels: dependencies
