Repository UK-Export-Finance/tfs-api, pull requests merged in 2025-05, with the labels that each got.

#1006 chore(GIFT-11501): update logs to use pino logger
  src/modules/gift/gift-http.service.test.ts
  src/modules/gift/gift-http.service.ts
  src/modules/gift/gift.controller.test.ts
  src/modules/gift/gift.counterparty.service.test.ts
  src/modules/gift/gift.counterparty.service.ts
  src/modules/gift/gift.fixed-fee.service.test.ts
  src/modules/gift/gift.fixed-fee.service.ts
  src/modules/gift/gift.obligation.service.test.ts
  src/modules/gift/gift.obligation.service.ts
  src/modules/gift/gift.repayment-profile.service.test.ts
  src/modules/gift/gift.repayment-profile.service.ts
  src/modules/gift/gift.service-createFacility-bad-requests.test.ts
  src/modules/gift/gift.service-createFacility-error-handling.test.ts
  src/modules/gift/gift.service-createFacility.test.ts
  src/modules/gift/gift.service-createInitialFacility.test.ts
  src/modules/gift/gift.service-getFacility.test.ts
  src/modules/gift/gift.service.ts
Labels: Type: chore

#1008 fix(deployment): moved dev dep to dep
  package-lock.json
  package.json
Labels: Type: Fix

#1015 feat(GIFT-10027): create a facility - approved status
  src/constants/examples/gift.examples.constant.ts
  src/constants/gift/gift.constant.ts
  src/modules/gift/custom-decorators/is-supported-currency.ts
  src/modules/gift/dto/facility-creation-response.ts
  src/modules/gift/dto/facility-creation.ts
  src/modules/gift/dto/facility-get.ts
  src/modules/gift/dto/facility-overview.ts
  src/modules/gift/dto/index.ts
  src/modules/gift/gift.counterparty.service.ts
  src/modules/gift/gift.currency.controller.test.ts
  src/modules/gift/gift.currency.service.ts
  src/modules/gift/gift.facility.controller.test.ts
  src/modules/gift/gift.facility.controller.ts
  src/modules/gift/gift.fixed-fee.service.ts
  src/modules/gift/gift.http.service.test.ts
  src/modules/gift/gift.http.service.ts
  src/modules/gift/gift.module.ts
  src/modules/gift/gift.obligation.service.ts
  src/modules/gift/gift.repayment-profile.service.ts
  src/modules/gift/gift.service-createFacility-approve-status-bad-requests.test.ts
  src/modules/gift/gift.service-createFacility-bad-requests.test.ts
  src/modules/gift/gift.service-createFacility-error-handling.test.ts
  src/modules/gift/gift.service-createFacility.test.ts
  src/modules/gift/gift.service-createInitialFacility.test.ts
  src/modules/gift/gift.service-getFacility.test.ts
  src/modules/gift/gift.service.ts
  src/modules/gift/gift.status.service.test.ts
  src/modules/gift/gift.status.service.ts
  test/gift/create-facility.api-test.ts
  test/http-response/index.ts
Labels: Type: chore, Type: Feature

#1016 feat(GIFT-11376): maximum amount validations
  src/constants/gift/validation.constant.ts
  src/modules/gift/dto/facility-overview.ts
  src/modules/gift/dto/fixed-fee.ts
  src/modules/gift/dto/repayment-profile-allocation.ts
  test/gift/assertions/array-of-nested-objects-number-validation.ts
  test/gift/assertions/array-of-objects-number-validation.ts
  test/gift/assertions/number-validation.ts
  test/gift/create-facility-validation-repayment-profiles.api-test.ts
  test/gift/create-facility-validation.api-test.ts
Labels: Type: chore, Type: Feature

#1023 chore(GIFT-12084): remove invalid open api field
  src/modules/gift/gift.currency.controller.ts
Labels: Type: chore, Type: Fix

#1024 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: Type: chore
