Repository UK-Export-Finance/tfs-api, pull requests merged in 2025-07, with the labels that each got.

#1068 chore(GIFT-12889): optimise async validation - product type
  package-lock.json
  package.json
  src/modules/facility/facility.service.ts
  src/modules/gift/controllers/gift.facility.controller.test.ts
  src/modules/gift/custom-decorators/index.ts
  src/modules/gift/custom-decorators/is-supported-product-type.ts
  src/modules/gift/dto/request/facility-creation.ts
  src/modules/gift/dto/request/facility-overview.ts
  src/modules/gift/gift.module.ts
  src/modules/gift/helpers/async-validation/generate-overview-validation-errors/index.test.ts
  src/modules/gift/helpers/async-validation/generate-overview-validation-errors/index.ts
  src/modules/gift/services/gift.facility-async-validation.service.test.ts
  src/modules/gift/services/gift.facility-async-validation.service.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-create.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-approve-status-bad-requests.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-async-validation-errors.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-bad-requests.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-error-handling.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createInitialFacility.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-get.test.ts
  test/gift/assertions/product-type-code-string-validation.ts
  test/gift/create-facility-validation-obligations.api-test.ts
Labels: Type: chore

#1071 chore(GIFT-12890): optimise async validation - counterparty role codes
  src/modules/gift/controllers/gift.facility.controller.test.ts
  src/modules/gift/custom-decorators/index.ts
  src/modules/gift/custom-decorators/is-supported-counterparty-role.ts
  src/modules/gift/dto/request/counterparty.ts
  src/modules/gift/dto/response/counterparty-role-gift-response.ts
  src/modules/gift/helpers/async-validation/generate-errors/index.test.ts
  src/modules/gift/helpers/async-validation/generate-errors/index.ts
  src/modules/gift/helpers/async-validation/generate-overview-errors/index.test.ts
  src/modules/gift/helpers/async-validation/generate-overview-errors/index.ts
  src/modules/gift/helpers/async-validation/generate-validation-errors/index.test.ts
  src/modules/gift/helpers/async-validation/generate-validation-errors/index.ts
  src/modules/gift/helpers/async-validation/index.ts
  src/modules/gift/services/gift.counterparty.service.test.ts
  src/modules/gift/services/gift.counterparty.service.ts
  src/modules/gift/services/gift.facility-async-validation.service.test.ts
  src/modules/gift/services/gift.facility-async-validation.service.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-create.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-approve-status-bad-requests.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-async-validation-errors.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-bad-requests.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-error-handling.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createInitialFacility.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-get.test.ts
  test/gift/assertions/array-of-objects-currency-string-validation.ts
  test/gift/assertions/array-of-objects-fee-type-code-string-validation.ts
  test/gift/assertions/array-of-objects-role-id-string-validation.ts
Labels: Type: chore

#1072 chore(GIFT-12891): optimise async validation - fixed fee codes
  src/constants/examples/gift.examples.constant.ts
  src/modules/gift/controllers/gift.facility.controller.test.ts
  src/modules/gift/custom-decorators/index.ts
  src/modules/gift/custom-decorators/is-supported-fee-type.ts
  src/modules/gift/dto/request/fixed-fee.ts
  src/modules/gift/dto/response/fee-type-gift-response.ts
  src/modules/gift/dto/response/index.ts
  src/modules/gift/services/gift.counterparty.service.test.ts
  src/modules/gift/services/gift.counterparty.service.ts
  src/modules/gift/services/gift.facility-async-validation.service.test.ts
  src/modules/gift/services/gift.facility-async-validation.service.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-create.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-approve-status-bad-requests.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-async-validation-errors.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-bad-requests.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createFacility-error-handling.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-createInitialFacility.test.ts
  src/modules/gift/services/gift.facility.service/gift.facility.service-get.test.ts
  src/modules/gift/services/gift.fee-type.service.test.ts
  src/modules/gift/services/gift.fee-type.service.ts
  test/gift/assertions/array-of-objects-fee-type-code-string-validation.ts
Labels: Type: chore

#1078 fix(chance-dependency): removed chance from dev dependency
  package-lock.json
  package.json
Labels: Type: Fix

#1079 chore(GIFT-13101): optimise async validation - counterparty share percentage
  src/constants/examples/gift.examples.constant.ts
  src/modules/gift/custom-decorators/counterparty-share-percentage-validation.ts
  src/modules/gift/custom-decorators/index.ts
  src/modules/gift/dto/request/counterparty.ts
  src/modules/gift/helpers/generate-counterparty-share-percentage-errors/index.test.ts
  src/modules/gift/helpers/generate-counterparty-share-percentage-errors/index.ts
  src/modules/gift/helpers/index.ts
  src/modules/gift/helpers/validate-counterparty-share-percentage/index.test.ts
  src/modules/gift/helpers/validate-counterparty-share-percentage/index.ts
  src/modules/gift/services/gift.counterparty.service.test.ts
  src/modules/gift/services/gift.counterparty.service.ts
  src/modules/gift/services/gift.facility-async-validation.service.test.ts
  src/modules/gift/services/gift.facility-async-validation.service.ts
  test/gift/assertions/array-of-objects-share-percentage-validation.ts
  test/gift/assertions/currency-string-validation.ts
  test/gift/create-facility-validation-counterparties-share-percentage.api-test.ts
  test/gift/test-helpers/index.ts
Labels: Type: chore

#1080 chore(deps): bumps
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: Type: chore

#1081 fix(GIFT-13101): counterparty sharePercentage validation
  src/modules/gift/dto/request/counterparty.ts
  src/modules/gift/helpers/generate-counterparty-share-percentage-errors/index.test.ts
  src/modules/gift/helpers/generate-counterparty-share-percentage-errors/index.ts
  test/gift/assertions/array-of-objects-share-percentage-validation.ts
  test/gift/create-facility-validation-counterparties-share-percentage.api-test.ts
Labels: Type: Bug, Type: Fix

#1102 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: Type: chore
