Repository UK-Export-Finance/tfs-api, pull requests merged in 2025-04, with the labels that each got.

#954 feat(GIFT-10497): endpoint versioning
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/app.ts
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/constants/application.constant.ts
  src/modules/gift/gift.controller.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/gift/get-facility-by-id.api-test.ts
  test/support/environment-variables.ts
Labels: Type: chore, Type: Feature

#953 feat(GIFT-9930): create a facility (overview)
  .cspell.json
  package-lock.json
  src/constants/countries.constant.ts
  src/constants/examples/examples.constant.ts
  src/constants/examples/gift.examples.constant.ts
  src/constants/gift.constant.ts
  src/constants/properties.constant.ts
  src/constants/ukef-id.constant.ts
  src/modules/gift/dto/facility-creation.ts
  src/modules/gift/dto/facility-get.ts
  src/modules/gift/dto/facility.ts
  src/modules/gift/dto/index.ts
  src/modules/gift/gift-http.service.test.ts
  src/modules/gift/gift-http.service.ts
  src/modules/gift/gift.controller.test.ts
  src/modules/gift/gift.controller.ts
  src/modules/gift/gift.service.test.ts
  src/modules/gift/gift.service.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/gift/assertions/boolean-validation.ts
  test/gift/assertions/generate-payload.ts
  test/gift/assertions/index.ts
  test/gift/assertions/number-validation.ts
  test/gift/assertions/response-assertion.ts
  test/gift/assertions/string-validation.ts
  test/gift/assertions/ukef-id-validation.ts
  test/gift/create-facility-validation.api-test.ts
  test/gift/create-facility.api-test.ts
  test/gift/get-facility-by-id.api-test.ts
  test/http-response/index.ts
Labels: Type: chore, Type: Feature

#966 feat(acr): acr purge workflow
  .cspell.json
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/acr/action.yml
  .github/actions/notify/action.yml
  .github/workflows/purge.yml
  package-lock.json
  package.json
Labels: Type: Feature

#968 feat(GIFT-10828): create a facility - obligorUrn validation
  src/constants/examples/gift.examples.constant.ts
  src/constants/gift.constant.ts
  src/modules/gift/dto/facility.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/gift/assertions/index.ts
  test/gift/assertions/number-string-validation.ts
  test/gift/create-facility-validation.api-test.ts
Labels: Type: Feature

#976 feat(GIFT-10023): create a facility (repayment profiles)
  src/constants/examples/gift.examples.constant.ts
  src/constants/gift.constant.ts
  src/modules/gift/dto/facility-creation.ts
  src/modules/gift/dto/index.ts
  src/modules/gift/dto/repayment-profile-allocation.ts
  src/modules/gift/dto/repayment-profile.ts
  src/modules/gift/gift.controller.test.ts
  src/modules/gift/gift.counterparty.service.ts
  src/modules/gift/gift.module.ts
  src/modules/gift/gift.repayment-profile.service.test.ts
  src/modules/gift/gift.repayment-profile.service.ts
  src/modules/gift/gift.service-createFacility-bad-requests.test.ts
  src/modules/gift/gift.service-createFacility-error-handling.test.ts
  src/modules/gift/gift.service-createFacility.test.ts
  src/modules/gift/gift.service-createInitialFacility.test.ts
  src/modules/gift/gift.service-getFacility.test.ts
  src/modules/gift/gift.service.ts
  src/modules/gift/helpers/index.ts
  src/modules/gift/helpers/map-all-validation-error-responses/index.test.ts
  src/modules/gift/helpers/map-all-validation-error-responses/index.ts
  src/modules/gift/helpers/map-validation-error-responses/index.ts
  src/types/index.d.ts
  test/gift/create-facility-validation-counterparties.api-test.ts
  test/gift/create-facility-validation.api-test.ts
  test/gift/create-facility.api-test.ts
  test/gift/get-facility-by-id.api-test.ts
Labels: Type: chore, Type: Docs, Type: Feature

#982 chore(GIFT-10023): create a facility - repayment profiles - api tests
  src/constants/gift.constant.ts
  src/modules/gift/dto/facility-creation.ts
  test/gift/assertions/array-of-nested-objects-number-validation.ts
  test/gift/assertions/array-of-nested-objects-string-validation.ts
  test/gift/assertions/array-of-objects-number-validation.ts
  test/gift/assertions/array-of-objects-string-validation.ts
  test/gift/assertions/generate-payload.ts
  test/gift/assertions/index.ts
  test/gift/assertions/response-assertion.ts
  test/gift/create-facility-validation-repayment-profiles.api-test.ts
  test/gift/create-facility-validation.api-test.ts
Labels: Type: chore

#983 feat(GIFT-11460): create a facility - repayment profiles - unique validation
  src/constants/examples/gift.examples.constant.ts
  src/modules/gift/custom-decorators/index.ts
  src/modules/gift/custom-decorators/unique-repayment-profile-allocation-dates.ts
  src/modules/gift/custom-decorators/unique-repayment-profile-names.ts
  src/modules/gift/dto/facility-creation.ts
  src/modules/gift/dto/index.ts
  src/modules/gift/helpers/array-has-unique-strings/index.test.ts
  src/modules/gift/helpers/array-has-unique-strings/index.ts
  src/modules/gift/helpers/get-repayment-profile-allocation-dates/index.test.ts
  src/modules/gift/helpers/get-repayment-profile-allocation-dates/index.ts
  src/modules/gift/helpers/get-repayment-profile-names/index.test.ts
  src/modules/gift/helpers/get-repayment-profile-names/index.ts
  src/modules/gift/helpers/index.ts
  test/gift/create-facility-validation-repayment-profiles.api-test.ts
  test/gift/create-facility-validation.api-test.ts
Labels: Type: chore, Type: Feature

#990 chore(GIFT-11499): unit test improvments
  .cspell.json
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/acr/action.yml
  .github/actions/notify/action.yml
  .github/workflows/purge.yml
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/modules/gift/gift-http.service.test.ts
  src/modules/gift/gift.controller.test.ts
  src/modules/gift/gift.counterparty.service.test.ts
  src/modules/gift/gift.repayment-profile.service.test.ts
  src/modules/gift/gift.service-createFacility-bad-requests.test.ts
  src/modules/gift/gift.service-createFacility-error-handling.test.ts
  src/modules/gift/gift.service-createFacility.test.ts
  src/modules/gift/gift.service-createInitialFacility.test.ts
  src/modules/gift/gift.service-getFacility.test.ts
  src/modules/gift/helpers/array-has-unique-strings/index.test.ts
  src/modules/gift/helpers/get-repayment-profile-allocation-dates/index.test.ts
  src/modules/gift/helpers/get-repayment-profile-names/index.test.ts
  src/modules/gift/helpers/map-all-validation-error-responses/index.test.ts
  src/modules/gift/helpers/map-responses-data/index.test.ts
  src/modules/gift/helpers/map-validation-error-responses/index.test.ts
Labels: Type: chore

#992 feat(GIFT-10026): create a facility (fixed fees)
  src/constants/examples/gift.examples.constant.ts
  src/constants/gift/gift.constant.ts
  src/constants/gift/validation.constant.ts
  src/modules/gift/dto/facility-creation.ts
  src/modules/gift/dto/fixed-fee.ts
  src/modules/gift/dto/index.ts
  src/modules/gift/gift.controller.test.ts
  src/modules/gift/gift.fixed-fee.service.test.ts
  src/modules/gift/gift.fixed-fee.service.ts
  src/modules/gift/gift.module.ts
  src/modules/gift/gift.service-createFacility-bad-requests.test.ts
  src/modules/gift/gift.service-createFacility-error-handling.test.ts
  src/modules/gift/gift.service-createFacility.test.ts
  src/modules/gift/gift.service-createInitialFacility.test.ts
  src/modules/gift/gift.service-getFacility.test.ts
  src/modules/gift/gift.service.ts
  src/modules/gift/helpers/map-all-validation-error-responses/index.test.ts
  src/modules/gift/helpers/map-all-validation-error-responses/index.ts
  test/gift/create-facility-validation-fixed-fees.api-test.ts
  test/gift/create-facility-validation.api-test.ts
  test/gift/create-facility.api-test.ts
Labels: Type: chore, Type: Feature
